apiVersion: v1
kind: Namespace
metadata:
  name: runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: runners
  name: runner-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch",]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: runners
  name: sa-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: runners
subjects:
- kind: ServiceAccount
  name: sa-runner 
  apiGroup: "" #rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: runner-role
  apiGroup: "" #rbac.authorization.k8s.io
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runnerdeployment
  namespace: runners
spec:
  replicas: 2
  template:
    spec:
      labels:
      - k8s
      repository: syslxg/github-runners
      containerMode: kubernetes
      serviceAccountName: sa-runner
      workVolumeClaimTemplate:
        storageClassName: standard
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      env: []