name: K8S runner env issue
env:
  foo: '{"user": "YWJjCg=="}'
on:
  workflow_dispatch:
jobs:
  envissue:
    runs-on: k8s
    container:
      image: ubuntu
    steps:
    - run: |
        sleep 1000
        apt-get update
        apt-get install -y jq
        echo "foo: $foo"        
        echo "$foo" | jq -r .user
